### ISSUE TITLE
Neu Ausgabe erstellen: Icon wird falsch angezeigt

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#11]
Wenn zweimal hintereinander eine neue Ausgaben-Kategorie erstellt wird und man dann eine Ausgabe dieser Kategorie erstellen will, gibt es einen Anzeigefehler des Kategorie-Icons (**siehe Screenshot**).

**Schritte zur Reproduktion:**
1. Neue Ausgaben-Kategorie erstellen (Eventuell dann eine Ausgabe dieser Kategorie erstellen) 
2. Nocheinmal neue Ausgaben-Kategorie erstellen
3. Ausgabe der neu erstellten Kategorie hinzufügen

**Screenshot:**
![Screenshot_20190617-191308_FinanzManager](https://user-images.githubusercontent.com/48477964/59623552-b30fe100-9134-11e9-93cc-b6d39232a149.jpg)

**Comment by mastalier1997** [comment]
Sollte angepasst sein mit dem neuen Push, Constraints wurden alle auf gleiche Größe angepasst was vorher nicht war
