### ISSUE TITLE
Neue Einnahme/Ausgabe erstellen: keine Kategorie

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#12]
Wenn man noch keine neue Einnahmen/Ausgaben -**Kategorie** erstellt hat und beim Hinzufügen einer neuen Einnahme/Ausgabe die Kategorie **für selbst erstellte Kategorien** auswählt, dann bleibt das Feld "Art" (also Kategorie) leer.

- Sollte vielleicht nicht auswählbar sein, solange noch keine Einnahme/Ausgabe erstellt wurde?

**Comment by mastalier1997** [comment]
Mit neuem Push behoben
