### ISSUE TITLE
unbeschränkte String-Länge bei Beschreibung und selbst erstellten Kategorien

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#13]
In die Beschreibung und in die selbst erstellte Kategorie können beliebig viele Zeichen eingefügt werden --> führt zu Anzeigefehlern, sollte begrenzt werden.

**Screenshot:**
![Screenshot_20190618-161742_FinanzManager](https://user-images.githubusercontent.com/48477964/59692423-2a04b280-91e5-11e9-82d5-97e11a4e5d72.jpg)

**Comment by RonaldMoritz** [comment]
### Gilt auch für Betrag (sollte max. 6-stellig sein)

**Comment by mastalier1997** [comment]
Limit für Kategoriename eingeführt mit neuem Push
