### ISSUE TITLE
Übersicht Ausgaben: Fehlerhafte Anzeige

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#16]
Wenn man in der Ausgaben Übersicht zuerst nach "Jahr und Monat" sortiert und einen Zeitraum auswählt in dem Ausgaben angezeigt werden **und dann** nach "Jahr und Quartal sortiert, werden diese Ausgaben weiterhin angezeigt. Sie überlappen sich auch mit den Ausgaben die bei "Jahr und Quartal" angezeigt werden.

**Screenshot:**
![Screenshot_20190618-185127_FinanzManager](https://user-images.githubusercontent.com/48477964/59703603-87efc500-91fa-11e9-8ee8-aeb896a70514.jpg)

**Comment by RonaldMoritz** [comment]
wahrscheinlich wird der listView für "Jahr und Monat" beim Wechsel auf "Jahr und Quartal" nicht auf `invisible` gestellt.

**Comment by mastalier1997** [comment]
Ist mit neuem Push behoben
