### ISSUE TITLE
Einnahmen/Ausgaben ohne Datums-Angabe

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#19]
Es ist möglich Einnahmen/Ausgaben ohne Datums-Angabe zu erstellen. Für diese wird anscheinend standartmäßig ein Datum irgendwann im Mai 2019 ausgewählt.

**Comment by mastalier1997** [comment]
Sollte mit neuem Push behoben worden sein
