### ISSUE TITLE
Fehlende Jahre im Spinner

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#22]
Jahre in denen keine Einnahme/Ausgabe erstellt wurde aber **wiederkehrende Positionen** enthalten, werden in Spinnern nicht angezeigt und sind nicht auswählbar.

**Screenshot:**
![Screenshot_20190619-205059_FinanzManager](https://user-images.githubusercontent.com/48477964/59792273-12582780-92d4-11e9-9f99-aa46f2254445.jpg)

**Comment by mastalier1997** [comment]
Auswahl von Jahren ist jetzt zwischen 2010 bis 2025 ohne Lücken
