### ISSUE TITLE
Datumsfehler beim erstellen neuer Einnahmen/Ausagaben

### ISSUE THREAD

**Issue by mahsum97** [mastalier1997/Software-Engineering-PR#23]
Wenn man neue Einnahmen oder Ausgaben erstellt und dann auf den Datums Button klickt, ist man einen Monat später im Kalender. Sprich statt 19.06 wird der 19.07 ausgewählt. Wenn man dann zurück auf 19.06 geht und dass bestätigt steht neben dem Button 19.05.2019. Nach dem bestätigen wird der Betrag aber im richtigen Monat (Juni) eingetragen.

**Comment by mastalier1997** [comment]
mit neuem Push behoben

**Comment by mahsum97** [comment]
falsches Datum steht noch neben dem Datums Button

**Comment by mahsum97** [comment]
Fehler behoben
