### ISSUE TITLE
Bei zu große Zahlen überlappen sich die Ausgabe/Einnahme/Balance

### ISSUE THREAD

**Issue by mastalier1997** [mastalier1997/Software-Engineering-PR#24]
Mögliche Lösungsidee: Wenn man die Größe des TextViews fix groß macht und dann dann die schrift einfach kleiner an einem bestimmten Betrag?
![Screenshot_20190620-082442](https://user-images.githubusercontent.com/48477843/59826236-30ef0a80-9336-11e9-845d-7ae9cd337afd.jpg)

**Comment by mahsum97** [comment]
TextView sind jetzt mit AutoSize dynamisch. Textgröße verringert sich bei größeren Beträgen
