### ISSUE TITLE
Löschen von Positionen

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#25]
Einnahmen bzw. Ausgaben die die gleiche `Description`  und `Value` haben werden beide gelöscht, wenn man eine davon auswählt zum Löschen in **Settings -> Löschen von wiederkehrenden Positionen**

**Comment by FlorianPoessl** [comment]
Workaround: Lösung des Problems würde ziemlich viele Änderungen verschiedenster Klassen und Methoden erfordern. Deshalbt ist es jetzt beim Erstellen einer sich wiederkehrenden Position nur mehr möglich, eine neue Position zu erstellen, wo Beschreibung und Wert noch nicht verwendet wurden.
