### ISSUE TITLE
Diverse UI Fehler

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#26]
Siehe Screenshots

**Screenshot:**
![Screenshot_20190623-143649_FinanzManager](https://user-images.githubusercontent.com/48477964/59976442-e0411100-95c4-11e9-98e7-083a80b461fd.jpg)
**Screenshot:**
![Screenshot_20190623-143657_FinanzManager](https://user-images.githubusercontent.com/48477964/59976443-e0d9a780-95c4-11e9-9ea7-0932c18c464b.jpg)
**Screenshot:**
![Screenshot_20190623-143355_FinanzManager](https://user-images.githubusercontent.com/48477964/59976444-e0d9a780-95c4-11e9-8648-1c57765576bf.jpg)

**Screenshot:**
![Screenshot_20190623-143413_FinanzManager](https://user-images.githubusercontent.com/48477964/59976445-e0d9a780-95c4-11e9-972d-6470c6bbd29f.jpg)

**Screenshot:**
![Screenshot_20190623-143428_FinanzManager](https://user-images.githubusercontent.com/48477964/59976446-e1723e00-95c4-11e9-98d8-cf0298483eaa.jpg)

**Screenshot:**
![Screenshot_20190623-143637_FinanzManager](https://user-images.githubusercontent.com/48477964/59976447-e1723e00-95c4-11e9-8621-ddd7d766018a.jpg)

**Screenshot:**
![Screenshot_20190623-143644_FinanzManager](https://user-images.githubusercontent.com/48477964/59976448-e20ad480-95c4-11e9-8df2-2682b88b99a5.jpg)

**Comment by mahsum97** [comment]
Text Fehler bei Neue Einnahmen / Ausgaben sollte gelöst sein, bitte um Rückmeldung

**Comment by RonaldMoritz** [comment]
Der Fehler war eigentlich schon behoben, hab vergessen hier zu posten @mahsum97
