### ISSUE TITLE
Betrag Anzeigefehler & Kommastellen keine Begrenzung

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#27]
Kommastellen für Betrag sollten auf 2 begrenzt werden, macht sonst keinen Sinn bei Geldbeträgen. Außerdem nimmt der Betrag bei voller Länge zu viel Platz ein.

**Screenshot:**
![Screenshot_20190623-143617_FinanzManager](https://user-images.githubusercontent.com/48477964/59976460-2d24e780-95c5-11e9-9b68-2e2fe7385b5d.jpg)

**Comment by mastalier1997** [comment]
Limit mit neuem Push hinzugefügt
