### ISSUE TITLE
Begrenzung für Datumsauswahl

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#28]
Da nur noch Datums zwischen 2010 und 2025 im Spinner angezeigt werden, kann man sich Positionen außerhalb dieses Zeitraums nicht mehr ansehen aber trotzdem noch erstellen - macht keinen Sinn.

**Comment by mahsum97** [comment]
Datumsbegrenzung beim Erstellen neuer Positionen für min = 2010 und max = 2025 eingefügt
