### ISSUE TITLE
Farbe ändern

### ISSUE THREAD

**Issue by FlorianPoessl** [mastalier1997/Software-Engineering-PR#29]
Hab bisher noch keine Möglichkeit gefunden, wie man den Hex wert im colors.xml ändert. Die Anpassung/Änderung der orangenen Farbe in der ganzen App einheitlich würde aber nur so funktioniere, da wir das orange teilweise auch im Code verwendet haben.

Wenn ich jetzt im colors.xml den Code manuell ändere würde es schon gehen - aber halt nicht als User in der App.

Lassen wir die Funktion weg?

**Comment by RonaldMoritz** [comment]
Wenns zu viel Arbeit ist, ja.

**Comment by FlorianPoessl** [comment]
es geht glaub ich nicht einmal mit themes weil wir eben die Farbe (z.B. für den Spinner) auch im Java Code verwendet haben. Das hätten wir von anfang an miteinplanen müssen

**Comment by mastalier1997** [comment]
Ja hab`s mir auch mal früher geschaut funktioniert nicht wirklich ohne dass die Struktur umbauen müssten
