### ISSUE TITLE
Toast Message wenn auf Einnahme/Ausgabe geklickt wird

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#30]
Wenn die Beschreibung zu lange ist um angezeigt zu werden, wird sie abgekürzt. Wäre vielleicht gut, wenn eine `Toast Message` mit voller Beschreibung angezeigt wird, wenn man auf die Position im ListView klickt. `Toast Messages` werden auch bei Import/Export verwendet (siehe Screenshot).
**Code für Toast-Message:** 
`//Toast Message`
` Context context = getApplicationContext();`
 `CharSequence text = "HIER SOLL DIE VOLLE BESCHREIBUNG STEHEN!";`
 `int duration = Toast.LENGTH_LONG;`
` Toast toast = Toast.makeText(context, text, duration);`
` toast.show();`

**Screenshot:**
![Screenshot_20190623-162309_FinanzManager](https://user-images.githubusercontent.com/48477964/59977637-d8d53400-95d3-11e9-98bd-e913aefd0b36.jpg)

**Comment by mastalier1997** [comment]
Ja wäre bestimmt nicht schlecht
