### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by mastalier1997** [mastalier1997/Software-Engineering-PR#5]
App crasht wenn in den Landscape Modus gewechselt wird

**Comment by RonaldMoritz** [comment]
Wenn man das Handy in den Landscape mode dreht und dann im Hauptmenü ein Untermenü auswählt (Einnahmen/Ausgaben/Graph/Import/Export), dreht sich die App noch immer in den Landscape mode. Wenn man Einnahme, Ausgabe oder Graph auswählt **stürzt** sie kurz darauf **noch immer ab**.

**Comment by RonaldMoritz** [comment]
### Fix:
**Im AndroidManifest.xml bei JEDER Activity `android:screenOrientation="portrait"` hinzufügen**

AndroidManifest.xml Screenshot:
![grafik](https://user-images.githubusercontent.com/48477964/59264911-7465bc80-8c44-11e9-9f5d-dc5bd861ae77.png)
