### ISSUE TITLE
Abgeschnittene Formatierung

### ISSUE THREAD

**Issue by mastalier1997** [mastalier1997/Software-Engineering-PR#6]
Teile des Design sind auf Geräte die nicht einem 18:9 Format abgeschnitten

**Comment by RonaldMoritz** [comment]
![grafik](https://user-images.githubusercontent.com/48477964/58906125-878c0000-870b-11e9-8ff1-9e538d702f77.png)

**Comment by RonaldMoritz** [comment]
### Screenshots Samsung A8 mit Bildformat 16:9

**Screenshot Graph:**
![grafik](https://user-images.githubusercontent.com/48477964/58906317-f6695900-870b-11e9-81a5-44c23d5b2fea.png)

**Screenshot Ausgaben Übersicht:**
![grafik](https://user-images.githubusercontent.com/48477964/58906363-08e39280-870c-11e9-9290-1365b31bb217.png)

**Screenshot Einnahmen Übersicht:**
![grafik](https://user-images.githubusercontent.com/48477964/58906423-23b60700-870c-11e9-9b8c-2fae50340354.png)

**Screenshot Hauptbildschirm:**
![grafik](https://user-images.githubusercontent.com/48477964/58906460-34667d00-870c-11e9-953c-950a2f575195.png)

**Comment by RonaldMoritz** [comment]
Behoben
