### ISSUE TITLE
DETAILIERTE Graphische Darstellung funktioniert nicht

### ISSUE THREAD

**Issue by RonaldMoritz** [mastalier1997/Software-Engineering-PR#8]
### Testcase:

![grafik](https://user-images.githubusercontent.com/48477964/58965606-24ed3f80-87b1-11e9-80a9-f73f0e3c50ae.png)

**Comment by mahsum97** [comment]
Struktur vom Aufbau der App muss umgeändert werden, was ich in dem verbleibenden Zeitraum nicht mehr möglich ist
